### ISSUE TITLE
Error with settings.ini file

### ISSUE THREAD

**Issue by jaeisma08** [UMN-Hydro/GSFLOW-GRASS#11]
I created a settings.ini file based on the template provided. However, when I try to run buildDomainGrass.py using the GRASS terminal, I receive the following message "Error opening or parsing input file." I am a brand new GRASS GIS user, and my python experience is largely from using ArcGIS. I am having trouble identifying the source of the above error. Could you please take a look at my input file and provide guidance and/or feedback? I am using GRASS 7.4.4 and Python 2.7.15. Thanks. 

A link to my input file is here: https://github.com/jaeisma08/GSFLOW-GRASS-test/blob/master/settings.ini

**Comment by jaeisma08** [comment]
I may have identified the cause of the problem, but nothing I have attempted has worked to fix it. It appears that Line 15 of the `buildDomainGrass.py` file (`from readSettings import Settings`) is not executing properly. When I run lines of the file individually, I receive the error `ImportError: No module named readSettings` at this line. I can see that the directory where the `readSettings.py` file is located is properly added to the sys.path. Also, I added a blank `__init__.py` file to both the domain_builder and Run folders. What do I need to do so that GRASS can find `readSettings.py`?

**Comment by huiyiyuxin** [comment]
Dear jaeisma08, I also meet with this problem, whether you have solved this problem. I think maybe the problem of python version. I can run gsflow-grass successful at this April, but it failed today.

**Comment by jaeisma08** [comment]
Dear huiyiyuxin, That is very possible. I could not get the software to work, so I am now using a different modeling program. Best of luck in troubleshooting the issue!

**Comment by awickert** [comment]
`readSettings.py` is located in the `Run` folder. Ideally, it should be in the path. I will look into this.

**Comment by awickert** [comment]
Everything seems to be working now. Please reopen an issue (and/or email me directly) if there are more problems.
