### ISSUE TITLE
Error with "r.cell.area" in buildDomainGRASS.py

### ISSUE THREAD

**Issue by zzusb** [UMN-Hydro/GSFLOW-GRASS#12]
I am using GRASS GIS 7.6+[the example of Cannon](https://github.com/UMN-Hydro/GSFLOW-GRASS-Cannon-River-Example)+python 2.7.17
This is the error output:

> python buildDomainGRASS.py G:\GSFLOW\input_tool_2\GSFLOW-GRASS-Cannon-River-Example-master\Cannon.ini
Importing raster map <DEM_original_import>...
Traceback (most recent call last):
  **File "buildDomainGRASS.py", line 89, in <module>
    r.cell_area(output=cellArea_meters2, units='m2',
overwrite=True)**
**File "D:\Program Files\GRASS GIS
7.6\etc\python\grass\pygrass\modules\shortcuts.py", line 59,
in __getattr__
    name.strip('_').replace('_', '.')))**
  File "D:\Program Files\GRASS GIS
7.6\etc\python\grass\pygrass\modules\interface\module.py",
line 530, in __init__
    raise GrassError(str_err % self.name)
grass.exceptions.GrassError: Error running: `r.cell.area
--interface-description`.
Using specified input file: G:\GSFLOW\input_tool_2\GSFLOW-GRASS-Cannon-River-Example-master\Cannon.ini
Importing DEM and generating hydrologic correction
OSError error(None): None

It seems like there is something wrong with the calculation of DEM cell area. I don't have no idea about this. Should I change the verson of GRASS GIS from 7.6 into 7.4?

**Comment by zzusb** [comment]
I try to re-install the "r.cell.area" extension, but there is an error

> WARNING: Extension <r.cell.area> already installed. Re-installing...
Downloading precompiled GRASS Addons <r.cell.area>...
ERROR: Extension <r.cell.area> not found

Those are the complete output:

> install_extensions                                                              
WARNING: Extension <v.gsflow.export> already installed. Re-installing...
Downloading precompiled GRASS Addons <v.gsflow.export>...
G:\GSFLOW\input_tool_2\GSFLOW-GRASS-master\domain_builder>(g.extension v.gsflow.gravres ) 
ERROR: Extension <v.gsflow.export> not found
WARNING: Extension <v.gsflow.gravres> already installed. Re-installing...
Downloading precompiled GRASS Addons <v.gsflow.gravres>...
G:\GSFLOW\input_tool_2\GSFLOW-GRASS-master\domain_builder>(g.extension v.gsflow.grid ) 
ERROR: Extension <v.gsflow.gravres> not found
WARNING: Extension <v.gsflow.grid> already installed. Re-installing...
Downloading precompiled GRASS Addons <v.gsflow.grid>...
ERROR: Extension <v.gsflow.grid> not found
G:\GSFLOW\input_tool_2\GSFLOW-GRASS-master\domain_builder>(g.extension v.gsflow.hruparams ) 
WARNING: Extension <v.gsflow.hruparams> already installed. Re-installing...
Downloading precompiled GRASS Addons <v.gsflow.hruparams>...
ERROR: Extension <v.gsflow.hruparams> not found
G:\GSFLOW\input_tool_2\GSFLOW-GRASS-master\domain_builder>(g.extension v.gsflow.reaches ) 
WARNING: Extension <v.gsflow.reaches> already installed. Re-installing...
Downloading precompiled GRASS Addons <v.gsflow.reaches>...
ERROR: Extension <v.gsflow.reaches> not found
G:\GSFLOW\input_tool_2\GSFLOW-GRASS-master\domain_builder>(g.extension v.gsflow.segments ) 
WARNING: Extension <v.gsflow.segments> already installed. Re-installing...
Downloading precompiled GRASS Addons <v.gsflow.segments>...
ERROR: Extension <v.gsflow.segments> not found
G:\GSFLOW\input_tool_2\GSFLOW-GRASS-master\domain_builder>(g.extension r.gsflow.hydrodem ) 
WARNING: Extension <r.gsflow.hydrodem> already installed. Re-installing...
Downloading precompiled GRASS Addons <r.gsflow.hydrodem>...
ERROR: Extension <r.gsflow.hydrodem> not found
G:\GSFLOW\input_tool_2\GSFLOW-GRASS-master\domain_builder>(g.extension v.stream.inbasin ) 
WARNING: Extension <v.stream.inbasin> already installed. Re-installing...
Downloading precompiled GRASS Addons <v.stream.inbasin>...
ERROR: Extension <v.stream.inbasin> not found
G:\GSFLOW\input_tool_2\GSFLOW-GRASS-master\domain_builder>(g.extension v.stream.network ) 
WARNING: Extension <v.stream.network> already installed. Re-installing...
Downloading precompiled GRASS Addons <v.stream.network>...
G:\GSFLOW\input_tool_2\GSFLOW-GRASS-master\domain_builder>(g.extension r.cell.area ) 
ERROR: Extension <v.stream.network> not found
WARNING: Extension <r.cell.area> already installed. Re-installing...
Downloading precompiled GRASS Addons <r.cell.area>...
ERROR: Extension <r.cell.area> not found
G:\GSFLOW\input_tool_2\GSFLOW-GRASS-master\domain_builder>(g.extension r.stream.basins ) 
WARNING: Extension <r.stream.basins> already installed. Re-installing...
Downloading precompiled GRASS Addons <r.stream.basins>...
G:\GSFLOW\input_tool_2\GSFLOW-GRASS-master\domain_builder>(g.extension r.hydrodem ) 
ERROR: Extension <r.stream.basins> not found
WARNING: Extension <r.hydrodem> already installed. Re-installing...
Downloading precompiled GRASS Addons <r.hydrodem>...
ERROR: Extension <r.hydrodem> not found

Didn't I install those extensions?

**Comment by zzusb** [comment]
I can't correctly install the extensions listed in the instruction. 
The following shows the extensions added in my computer:(..\GRASS7\addons\bin)
![image](https://user-images.githubusercontent.com/49806989/68656091-22ff8780-056c-11ea-8381-b378d7c0d22a.png)
I think the .bat or something related to r.cell.area is lacking in the \bin floder.

**Comment by zzusb** [comment]
Those extensions for windows is not accessible.
[http://wingrass.fsv.cvut.cz/grass76/x86_64/addons/latest/logs/](url)

**Comment by zzusb** [comment]
I have changed to linux. It works at least for installing extensions and preliminarily running GIS part.

**Comment by awickert** [comment]
GRASS GIS was having problems with their extensions manager for some time. This should now be fixed.
