### ISSUE TITLE
ERROR with GIS part: failed to add field name "XXX" and failed with running PRMS

### ISSUE THREAD

**Issue by zzusb** [UMN-Hydro/GSFLOW-GRASS#13]
Some field can't be added to the gis field. I have no idea about it. How do I solve this error? Could anyone give me a hint? The follows are part of error output:

> WARNING: OGR layer <HRUs> already exists and will be overwritten
ERROR 6: Failed to add field named 'hru_area_m2'
ERROR 6: Failed to add field named 'hru_segment'
ERROR 6: Failed to add field named 'obsin_segment'
ERROR 6: Failed to add field named 'aspect_x_sum'
ERROR 6: Failed to add field named 'aspect_y_sum'
WARNING: OGR layer <gravity_reservoirs> already exists and will be overwritten
ERROR 6: Failed to add field named 'a_hru_aspect'
ERROR 6: Failed to add field named 'a_hru_slope'
ERROR 6: Failed to add field named 'a_outlet_sta'
ERROR 6: Failed to add field named 'a_hru_xlong'
ERROR 6: Failed to add field named 'a_hru_segment'
ERROR 6: Failed to add field named 'a_obsin_segment'
ERROR 6: Failed to add field named 'a_soil_type'
ERROR 6: Failed to add field named 'a_aspect_x_sum'
ERROR 6: Failed to add field named 'a_aspect_y_sum'
ERROR 6: Failed to add field named 'b_basinmask'
ERROR 6: Failed to add field named 'gvr_cell_id'
ERROR 6: Failed to add field named 'hru_area_m2'
ERROR 6: Failed to add field named 'cell_area_m2'
ERROR 6: Failed to add field named 'gvr_cell_pct'
ERROR 6: Failed to add field named 'gvr_hru_pct'

I think this error may cause the failure of running GSFLOW. The last part (running GSFLOW) of goGSFLOW.py was not successfully run. Those are the our records of running PRMS:

> WARNING: parameter 'adj_by_hru' is not required; file is ../inputs/PRMS_GSFLOW/CannonRiver_2layer_60mDEM_1200mMODFLOW_GSFLOW.param; line number 23109
> WARNING: pt_alpha[0] = 0.750000 is out of range (1.000000 to 2.000000); file is ../inputs/PRMS_GSFLOW/CannonRiver_2layer_60mDEM_1200mMODFLOW_GSFLOW.param; line number 33503
> 
> WARNING: parameter 'mnsziter' is not required; file is ../inputs/PRMS_GSFLOW/CannonRiver_2layer_60mDEM_1200mMODFLOW_GSFLOW.param; line number 40376
> 
> WARNING: parameter 'szconverge' is not required; file is ../inputs/PRMS_GSFLOW/CannonRiver_2layer_60mDEM_1200mMODFLOW_GSFLOW.param; line number 40383
> 
> WARNING: parameter 'print_freq' is not required; file is ../inputs/PRMS_GSFLOW/CannonRiver_2layer_60mDEM_1200mMODFLOW_GSFLOW.param; line number 43456
> 
> WARNING: parameter 'print_type' is not required; file is ../inputs/PRMS_GSFLOW/CannonRiver_2layer_60mDEM_1200mMODFLOW_GSFLOW.param; line number 43463
> ERROR - CHECK_ani_vars: **sat_recharge** is not a valid animation output variable.
> Set animation variables: sat_recharge is not a valid stat variable.

I used the latest example of Cannon. The version of GRASS GIS is 7.6 of Ubuntu. Maybe those problem can be own to the unstable GRASS GIS on ubuntu?

**Comment by zzusb** [comment]
The column name is too long (exceed 10 charactes) to export to an ESRI Shapefile.

**Comment by awickert** [comment]
These errors occur because of the Shapefile limitations, but cause no problems with the actual run. Note in the README where we indicate that you should ignore them :)

See #14. We might just update to exporting a different format (e.g., GPKG), but Shapefile is so common...
