### ISSUE TITLE
plotHRUvars.py issues

### ISSUE THREAD

**Issue by Lauren-Somers** [UMN-Hydro/GSFLOW-GRASS#2]
**plotHRUvars.py**
Line 125 was giving an error for the index being out of range. Changed the reference to i to i-1 and it seems to plot the right dates. So the line now reads:
_polys.append(ax.fill(_x, _y, facecolor=colors[i-1], edgecolor='k')[0])
-	As I mentioned before, unfortunately 1.2.2 has different names in the output csv so this should only work with 1.2.0.
-	No units on the colour bar.
-	Precip is plotted in inches, maybe we should convert to mm?
-	I see my sat_recharge is super high at first not necessarily a problem with the plotting script but not sure where this comes from?

**Comment by awickert** [comment]
Quick update:
* 2.0 issues not going to be fixed until the USGS finalizes it.
* Units and colorbar label noted; will hold off on fixing until we decide on whether we will have just one plotting script or many. It is also possible that the USGS will create NetCDF output, making these scripts less necessary thanks to viewers like Panoply.
* Most of our plots have now been consolidated, but this one still stands alone and most issues still remain.
* Not a clue on sat_recharge... perhaps something from spinup?

**Comment by awickert** [comment]
* Addressed the first 3 issues
* In the future, should create uniform parsers for all plotting codes instead of needing to edit them to change output file names (maybe a user will want to do this :) ?)
* Assuming that the last issue is just the model spin-up phase as before.

Closing.
