### ISSUE TITLE
Docker compose 'cannot touch /usr/lib/grass74/docs/html/...'

### ISSUE THREAD

**Issue by dgketchum** [UMN-Hydro/GSFLOW-GRASS#22]
Seems gsflow_grass_docker/install_grass_package command runs `touch /usr/lib/grass74/docs/html/grass_logo.png` but the directory isn't there. I got around it by adding `mkdir -p /usr/lib/grass74/docs/html` before the touch commands.

**Comment by awickert** [comment]
Thanks for this! I am making a note here to update the README at some point -- and you should feel free to do so and issue a PR as well. I'm not sure just how out of date all of GSFLOW-GRASS might be by now.

**Comment by awickert** [comment]
@dgketchum: Should https://github.com/UMN-Hydro/GSFLOW-GRASS/pull/24 fix this?
