### ISSUE TITLE
docker installs grass78 (which uses Python 3.x)

### ISSUE THREAD

**Issue by dgketchum** [UMN-Hydro/GSFLOW-GRASS#23]
The install_grass_package script, as called from the Dockerfile, installs the latest GRASS (7.8 as of today). Since the software is tested on GRASS 7.6, I had to make some changes to the Dockerfile and install_grass_package to get Ubuntu 16.04 and Grass76:

in Docker file, changed
`FROM ubuntu:18.10`
to 
`FROM ubuntu:16.04`

in install_grass_package, changed
`apt install -y software-properties-common
add-apt-repository ppa:ubuntugis/ubuntugis-unstable`
to
`apt install -y software-properties-common
add-apt-repository ppa:ubuntugis/ppa
add-apt-repository ppa:grass/grass-stable
apt-get update
apt-get install grass76`

**Comment by awickert** [comment]
Thanks for this as well, and like my comment on https://github.com/UMN-Hydro/GSFLOW-GRASS/issues/22, I'm very glad to support your help and/or PRs. I hope that you're able to get GSFLOW-GRASS up and running!

**Comment by awickert** [comment]
@dgketchum: Should https://github.com/UMN-Hydro/GSFLOW-GRASS/pull/24 fix this? If so, please close, or I can.
