### ISSUE TITLE
plotSegmentDischarge.py issues

### ISSUE THREAD

**Issue by Lauren-Somers** [UMN-Hydro/GSFLOW-GRASS#3]
**plotSegmentDischarge.py**

Concatenation error on line 125. 
ax.set_title(plotting_variable+': '+ date)
The first number in the matrix dates is nan which means the variable is considered float so it doesn’t want to concatenate. I think this is just symptomatic of the next issue.
In the meantime I changed to 
ax.set_title(plotting_variable+': '+ str(date))
Next I get an error with writer.grab_frame() on line 129. Also nothing shows up in the plot area of the graph in the console and it writes a movie but nothing shows up in the plot.
I believe this is an issue with reading in the “…ani.nsegment.corrected” file because the data frame “segment_outputs” is not reading in correctly. It’s mostly nans. I tried changing the number of line to skip from 8 to 10 which makes “segments_outputs” look better but then I run into more issues. 
I keep getting 10d etc showing up "segments_outputs" and the first line of dates, even when I try to skip over more lines?

Small things:
-	Prints a bunch of HRU numbers in the console every time step. Why do we want this? It makes it hard to scroll back up.
-	No units on colour bar

**Comment by Lauren-Somers** [comment]
Here are my output files for this plotting script in case you want to compare with yours.

[Shullcas_7.ani.nsegment.corrected.txt](https://github.com/UMN-Hydro/GSFLOW-GRASS/files/1483906/Shullcas_7.ani.nsegment.corrected.txt)
[Shullcas_7.ani.nsegment.txt](https://github.com/UMN-Hydro/GSFLOW-GRASS/files/1483907/Shullcas_7.ani.nsegment.txt)

**Comment by awickert** [comment]
I have corrected the animation code so it should fix these as well. Could you test again and post your corrected.txt file if the updated version does not work?

**Comment by awickert** [comment]
I am assuming that the update from last year succeeded; closing. Please re-open if there is an issue.
