### ISSUE TITLE
2 Settings files?

### ISSUE THREAD

**Issue by Lauren-Somers** [UMN-Hydro/GSFLOW-GRASS#4]
There is a Settings.ini file in with the Domain Builder. It has different format than the one in the Run folder. Should these be the same? Are they both necessary?

**Comment by awickert** [comment]
The domain builder one is old and no longer used; I've removed it. The current one is `settings_template_proposed.ini`, and has a similar form to those in the *.tar.gz I sent you.

Thanks for noticing this -- confusing indeed!
