### ISSUE TITLE
Visualization script instructions in Readme

### ISSUE THREAD

**Issue by Lauren-Somers** [UMN-Hydro/GSFLOW-GRASS#8]
When using plotMODFLOW.py, the Readme says use this syntax:
`run (visualization_script).py (Settings File full path)`
But I need to use something with at least one flag
`run plotMODFLOW.py -i (Settings File full path) -p wtd -o TEST.mp4`

**Comment by awickert** [comment]
I see that `plotMODFLOW.py` has a configuration parser whereas the others do not. I have updated the README.md.
